platform :ios,'8.0'
pod 'AFNetworking','~>3.0.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.0'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'ObjectiveGumbo', '~> 0.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'FMDB', '~> 2.6'
